name: Build PSP Homebrew

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pspdev/pspdev:latest

    steps:
      - name: Repo'yu indir
        uses: actions/checkout@v4

      - name: PSP Homebrew derle
        run: make

      - name: Build dosyalarını yükle
        uses: actions/upload-artifact@v4
        with:
          name: PSP-Build
          path: |
            *.elf
            *.prx
            EBOOT.PBP